POST http://localhost:3000/produtos/incluir 
Content-Type: application/json

{
    "img": "./img/product.png",
    "codBarra": "867900567894",
    "nomeItem": "camiseta2040-",
    "tamanhoItem": "M",
    "precoItem": 39.90,
    "estoque": 3,
    "qtd": 0
}

###

DELETE http://localhost:3000/produtos/excluir
Content-Type: application/json

{
    "_id":"629ee1a1ba5ae1dfc9936743"
}

###

GET http://localhost:3000/produtos/listar
Content-Type: application/json

